-- MySQL Script generated by MySQL Workbench
-- Tue Aug 30 17:38:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema promonline_o28g05
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema promonline_o28g05
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `promonline_o28g05` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `promonline_o28g05` ;

-- -----------------------------------------------------
-- Table `promonline_o28g05`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`categoria` (
  `id_categoriaprod` VARCHAR(15) NOT NULL,
  `nombre_categoriaprod` VARCHAR(50) NOT NULL,
  `descripcion_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoriaprod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `promonline_o28g05`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`producto` (
  `id_prod` VARCHAR(15) NOT NULL,
  `nombre_prod` VARCHAR(50) NOT NULL,
  `marca_prod` VARCHAR(50) NOT NULL,
  `desc_prod` VARCHAR(15) NULL DEFAULT NULL,
  `valorUnitVta_prod` DOUBLE NOT NULL,
  `stock_prod` VARCHAR(15) NOT NULL,
  `id_categoriaprod` VARCHAR(11) NOT NULL,
  `tipo_prove` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_prod`),
  INDEX `producto_id_categoriaprod_fk` (`id_categoriaprod` ASC) VISIBLE,
  CONSTRAINT `producto_id_categoriaprod_fk`
    FOREIGN KEY (`id_categoriaprod`)
    REFERENCES `promonline_o28g05`.`categoria` (`id_categoriaprod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `promonline_o28g05`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`cliente` (
  `id_cli` VARCHAR(15) NOT NULL,
  `id_prod` VARCHAR(15) NOT NULL,
  `nombre_cli` VARCHAR(60) NOT NULL,
  `apellido_cli` VARCHAR(60) NOT NULL,
  `identificacion_cli` VARCHAR(15) NOT NULL,
  `ciudad_cli` VARCHAR(50) NOT NULL,
  `direccion_cli` VARCHAR(100) NOT NULL,
  `edad_cli` VARCHAR(2) NULL DEFAULT NULL,
  `genero_cli` VARCHAR(1) NOT NULL,
  `tel_cli` VARCHAR(20) NOT NULL,
  `email_cli` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cli`),
  INDEX `cliente_id_prod_pf` (`id_prod` ASC) VISIBLE,
  CONSTRAINT `cliente_id_prod_pf`
    FOREIGN KEY (`id_prod`)
    REFERENCES `promonline_o28g05`.`producto` (`id_prod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `promonline_o28g05`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`detalleventa` (
  `num_detalle` VARCHAR(15) NOT NULL,
  `id_cli` VARCHAR(15) NOT NULL,
  `cantidad_articulo` VARCHAR(10) NOT NULL,
  `total_venta` DOUBLE NOT NULL,
  PRIMARY KEY (`num_detalle`),
  INDEX `detalleventa_id_cli_pf` (`id_cli` ASC) VISIBLE,
  CONSTRAINT `detalleventa_id_cli_pf`
    FOREIGN KEY (`id_cli`)
    REFERENCES `promonline_o28g05`.`cliente` (`id_cli`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `promonline_o28g05`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`factura` (
  `num_factura` VARCHAR(15) NOT NULL,
  `num_detalle` VARCHAR(15) NOT NULL,
  `fecha_factura` DATE NOT NULL,
  `num_pago` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`num_factura`),
  INDEX `factura_num_detalle_pf` (`num_detalle` ASC) VISIBLE,
  CONSTRAINT `factura_num_detalle_pf`
    FOREIGN KEY (`num_detalle`)
    REFERENCES `promonline_o28g05`.`detalleventa` (`num_detalle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `promonline_o28g05`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`proveedor` (
  `id_prove` VARCHAR(15) NOT NULL,
  `valorUnitCompra_prod` DOUBLE NOT NULL,
  `nom_prove` VARCHAR(50) NOT NULL,
  `ident_prove` VARCHAR(18) NOT NULL,
  `tel_prove` VARCHAR(23) NOT NULL,
  `email_prove` VARCHAR(50) NOT NULL,
  `direc_prove` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_prove`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `promonline_o28g05`.`producto_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promonline_o28g05`.`producto_proveedor` (
  `id_prod` VARCHAR(15) NOT NULL,
  `id_prove` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_prod`, `id_prove`),
  INDEX `producto_proveedor_id_prove_fk` (`id_prove` ASC) VISIBLE,
  CONSTRAINT `producto_proveedor_id_prod_fk`
    FOREIGN KEY (`id_prod`)
    REFERENCES `promonline_o28g05`.`producto` (`id_prod`),
  CONSTRAINT `producto_proveedor_id_prove_fk`
    FOREIGN KEY (`id_prove`)
    REFERENCES `promonline_o28g05`.`proveedor` (`id_prove`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
